version: '3.8'

# Development-specific docker-compose configuration
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  fire:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      RUST_LOG: fire=debug,tower_http=debug,sqlx=debug
      RUST_BACKTRACE: 1
    volumes:
      - ./src:/app/src:ro
      - ./migrations:/app/migrations:ro
      - cargo_cache:/usr/local/cargo/registry
    command: cargo run
    stdin_open: true
    tty: true

volumes:
  cargo_cache:
